=== randovania/factorio-randovania-mod/src/factorio_randovania_mod/files/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "configuration_identifier": {
            "type": "string",
            "description": "An unique identifier for this configuration. Only save files created with this identifier can be loaded."
        },
        "layout_uuid": {
            "description": "An UUID exposed via a global lua variable",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "technologies": {
            "description": "List of custom technologies to create.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "tech_name": {
                        "description": "Internal name of the technology",
                        "type": "string"
                    },
                    "locale_name": {
                        "description": "Name of the technology",
                        "type": "string"
                    },
                    "description": {
                        "description": "Description of the technology",
                        "type": "string"
                    },
                    "icon": {
                        "description": "Factorio filepath for the icon to use",
                        "type": "string"
                    },
                    "icon_size": {
                        "description": "Set the size of the icon image",
                        "type": "integer",
                        "default": 256
                    },
                    "cost_reference": {
                        "description": "The technology to use for research cost and prerequisites",
                        "type": "string"
                    },
                    "prerequisites": {
                        "description": "List of which technologies must be researched before",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "unlocks": {
                        "description": "List of which technologies are granted when this is researched.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "additionalProperties": false,
                "required": ["locale_name", "description", "icon","prerequisites", "unlocks"]
            }
        },
        "recipes": {
            "description": "Modify given recipes",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "recipe_name": {
                        "type": "string",
                        "description": "Name of the recipe to modify"
                    },
                    "category": {
                        "type": "string",
                        "description": "New crafting category to use for the recipe"
                    },
                    "ingredients": {
                        "type": "array",
                        "description": "The new costs of the recipe",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "description": "Item name of this ingredient"
                                },
                                "amount": {
                                    "type": "integer",
                                    "description": "How many copies of the ingredient are used"
                                },
                                "type": {
                                    "type": "string",
                                    "description": "What kind of ingredient it is",
                                    "enum": ["item", "fluid"],
                                    "default": "item"
                                }
                            },
                            "additionalProperties": false,
                            "required": ["name", "amount"]
                        }
                    }
                },
                "additionalProperties": false,
                "required": ["recipe_name", "category", "ingredients"]
            }
        },
        "starting_tech": {
            "description": "List of technologies that you start the game with",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "configuration_identifier",
        "layout_uuid",
        "technologies",
        "recipes",
        "starting_tech"
    ],
    "additionalProperties": false,
    "$defs": {
    }
}

=== randovania/factorio-randovania-mod/tests/test_files/patcher_a.json
{
    "configuration_identifier": "546NEMF5",
    "layout_uuid": "00000000-0000-1111-0000-000000000000",
    "technologies": [
        {
            "tech_name": "randovania-steam-power",
            "cost_reference": "steam-power",
            "locale_name": "Automation Science Pack",
            "description": "",
            "icon": "__base__/graphics/technology/automation-science-pack.png",
            "icon_size": 256,
            "prerequisites": [],
            "unlocks": [
                "automation-science-pack"
            ]
        },
        {
            "tech_name": "randovania-electronics",
            "cost_reference": "electronics",
            "locale_name": "Spidertron",
            "description": "",
            "icon": "__base__/graphics/technology/spidertron.png",
            "icon_size": 256,
            "prerequisites": [],
            "unlocks": [
                "spidertron"
            ]
        },
        {
            "tech_name": "randovania-automation-science-pack",
            "cost_reference": "automation-science-pack",
            "locale_name": "Construction Robotics",
            "description": "",
            "icon": "__base__/graphics/technology/construction-robotics.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-steam-power",
                "randovania-electronics"
            ],
            "unlocks": [
                "construction-robotics"
            ]
        },
        {
            "tech_name": "randovania-electric-mining-drill",
            "cost_reference": "electric-mining-drill",
            "locale_name": "Military",
            "description": "Provides the following in order: Military, Military 2, Military 3, Military 4.",
            "icon": "__base__/graphics/technology/military.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "military",
                "military-2",
                "military-3",
                "military-4"
            ]
        },
        {
            "tech_name": "randovania-repair-pack",
            "cost_reference": "repair-pack",
            "locale_name": "Logistic Science Pack",
            "description": "",
            "icon": "__base__/graphics/technology/logistic-science-pack.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "logistic-science-pack"
            ]
        },
        {
            "tech_name": "randovania-radar",
            "cost_reference": "radar",
            "locale_name": "Steel Processing",
            "description": "",
            "icon": "__base__/graphics/technology/steel-processing.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "steel-processing"
            ]
        },
        {
            "tech_name": "randovania-automation",
            "cost_reference": "automation",
            "locale_name": "Logistics",
            "description": "Provides the following in order: Logistics, Logistics 2, Logistics 3.",
            "icon": "__base__/graphics/technology/logistics-1.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "logistics",
                "logistics-2",
                "logistics-3"
            ]
        },
        {
            "tech_name": "randovania-logistic-science-pack",
            "cost_reference": "logistic-science-pack",
            "locale_name": "Logistics",
            "description": "Provides the following in order: Logistics, Logistics 2, Logistics 3.",
            "icon": "__base__/graphics/technology/logistics-1.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "logistics",
                "logistics-2",
                "logistics-3"
            ]
        },
        {
            "tech_name": "randovania-steel-processing",
            "cost_reference": "steel-processing",
            "locale_name": "Circuit Network",
            "description": "",
            "icon": "__base__/graphics/technology/circuit-network.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "circuit-network"
            ]
        },
        {
            "tech_name": "randovania-military",
            "cost_reference": "military",
            "locale_name": "Steel Axe",
            "description": "",
            "icon": "__base__/graphics/technology/steel-axe.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "steel-axe"
            ]
        },
        {
            "tech_name": "randovania-fast-inserter",
            "cost_reference": "fast-inserter",
            "locale_name": "Inserter",
            "description": "Provides the following in order: Inserter, Fast inserter, Bulk inserter.",
            "icon": "__base__/graphics/technology/fast-inserter.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "inserter",
                "fast-inserter",
                "bulk-inserter"
            ]
        },
        {
            "tech_name": "randovania-logistics",
            "cost_reference": "logistics",
            "locale_name": "Concrete",
            "description": "",
            "icon": "__base__/graphics/technology/concrete.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "concrete"
            ]
        },
        {
            "tech_name": "randovania-lamp",
            "cost_reference": "lamp",
            "locale_name": "Mining Productivity",
            "description": "",
            "icon": "__base__/graphics/technology/mining-productivity.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "mining-productivity-4"
            ]
        },
        {
            "tech_name": "randovania-gun-turret",
            "cost_reference": "gun-turret",
            "locale_name": "Electronics",
            "description": "Provides the following in order: Electronics, Advanced circuit, Processing unit.",
            "icon": "__base__/graphics/technology/electronics.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "electronics",
                "advanced-circuit",
                "processing-unit"
            ]
        },
        {
            "tech_name": "randovania-stone-wall",
            "cost_reference": "stone-wall",
            "locale_name": "Inserter",
            "description": "Provides the following in order: Inserter, Fast inserter, Bulk inserter.",
            "icon": "__base__/graphics/technology/fast-inserter.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation-science-pack"
            ],
            "unlocks": [
                "inserter",
                "fast-inserter",
                "bulk-inserter"
            ]
        },
        {
            "tech_name": "randovania-landfill",
            "cost_reference": "landfill",
            "locale_name": "Oil Gathering",
            "description": "",
            "icon": "__base__/graphics/technology/oil-gathering.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-logistic-science-pack"
            ],
            "unlocks": [
                "oil-gathering"
            ]
        },
        {
            "tech_name": "randovania-toolbelt",
            "cost_reference": "toolbelt",
            "locale_name": "Barrel Handling",
            "description": "",
            "icon": "__base__/graphics/icons/fluid/barreling/empty-barrel.png",
            "icon_size": 64,
            "prerequisites": [
                "randovania-logistic-science-pack"
            ],
            "unlocks": [
                "fluid-handling"
            ]
        },
        {
            "tech_name": "randovania-circuit-network",
            "cost_reference": "circuit-network",
            "locale_name": "Military",
            "description": "Provides the following in order: Military, Military 2, Military 3, Military 4.",
            "icon": "__base__/graphics/technology/military.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-logistic-science-pack"
            ],
            "unlocks": [
                "military",
                "military-2",
                "military-3",
                "military-4"
            ]
        },
        {
            "tech_name": "randovania-automation-c",
            "cost_reference": "automation-2",
            "locale_name": "Railway",
            "description": "",
            "icon": "__base__/graphics/technology/railway.png",
            "icon_size": 256,
            "prerequisites": [
                "randovania-automation",
                "randovania-steel-processing",
                "randovania-logistic-science-pack"
            ],
            "unlocks": [
                "railway"
            ]
        },
        {
            "tech_name": "randovania-steel-axe",
